# Generated by Django 6.1.1 on 2026-09-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=0, editable=False, help_text="Faqat shop.services.adjust_balance() orqali o'zgartiriladi.", verbose_name='cinepoint balansi'),
        ),
    ]
