# Generated by Django 6.1.1 on 2026-09-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_continue_watching',
            field=models.BooleanField(default=True, help_text="O'chirilsa, bosh sahifada davom etayotgan filmlar bo'limi umuman chiqmaydi. Foydalanuvchi buni bosh sahifadagi bo'lim ustidagi «Yashirish» tugmasi orqali ham o'chira oladi.", verbose_name="bosh sahifada «Davom ettirish» bo'limini ko'rsatish"),
        ),
    ]
