services:
  db:
    image: postgres:16-alpine
    container_name: moremovie_db
    environment:
      POSTGRES_DB: moremovie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: moremovie_web
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/moremovie
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
