# Generated by Django 6.1.1 on 2026-09-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ism')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=200, verbose_name='mavzu')),
                ('message', models.TextField(max_length=3000, verbose_name='xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="o'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yuborilgan')),
            ],
            options={
                'verbose_name': 'murojaat',
                'verbose_name_plural': 'murojaatlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='core_contac_is_read_67cbaf_idx')],
            },
        ),
    ]
