# Generated by Django 6.1.1 on 2026-09-06 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_dashboard', 'Boshqaruv paneliga kirish'), ('view_analytics', "Analitikani ko'rish"), ('manage_settings', 'Sayt sozlamalarini boshqarish'), ('manage_banners', 'Bannerlarni boshqarish'), ('send_notifications', 'Bildirishnoma yuborish'), ('manage_roles', 'Rollarni boshqarish'), ('manage_homepage', "Bosh sahifa bo'limlarini boshqarish")],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', 'Yangilandi'), ('delete', "O'chirildi"), ('publish', 'Chop etildi/yashirildi'), ('moderate', 'Moderatsiya qilindi'), ('send', 'Yuborildi'), ('settings', "Sozlamalar o'zgartirildi")], max_length=20, verbose_name='harakat')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, help_text="Obyekt o'chirilgandan keyin ham o'qilishi uchun matn ko'rinishida saqlanadi.", max_length=200, verbose_name='nishon tavsifi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vaqti')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_actions', to=settings.AUTH_USER_MODEL, verbose_name='bajaruvchi')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'faoliyat yozuvi',
                'verbose_name_plural': 'faoliyat yozuvlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dashboard_a_created_f2d914_idx')],
            },
        ),
    ]
