# Generated by Django 6.1.1 on 2026-09-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_dashboard', 'Boshqaruv paneliga kirish'), ('view_analytics', "Analitikani ko'rish"), ('manage_settings', 'Sayt sozlamalarini boshqarish'), ('manage_banners', 'Bannerlarni boshqarish'), ('send_notifications', 'Bildirishnoma yuborish'), ('manage_roles', 'Rollarni boshqarish'), ('manage_homepage', "Bosh sahifa bo'limlarini boshqarish"), ('manage_balance', 'Cinepoint balansini boshqarish')]},
        ),
    ]
