# Generated by Django 6.1.1 on 2026-09-03 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000, verbose_name='sharh')),
                ('status', models.CharField(choices=[('pending', 'Moderatsiyada'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10, verbose_name='holat')),
                ('moderator_note', models.CharField(blank=True, help_text="Ichki foydalanish uchun — saytda ko'rinmaydi.", max_length=200, verbose_name='moderator izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
            ],
            options={
                'verbose_name': 'sharh',
                'verbose_name_plural': 'sharhlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='baho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie', verbose_name='film')),
            ],
            options={
                'verbose_name': 'reyting',
                'verbose_name_plural': 'reytinglar',
                'ordering': ['-updated_at'],
            },
        ),
    ]
