# Generated by Django 6.1.1 on 2026-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Moderatsiyada'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('reported', 'Shikoyat qilingan'), ('spam', 'Spam')], default='pending', max_length=10, verbose_name='holat'),
        ),
    ]
