# Generated by Django 6.1.1 on 2026-09-13 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_director'),
        ('reviews', '0003_alter_review_status'),
        ('series', '0007_series_avg_rating_series_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='series.series', verbose_name='serial'),
        ),
        migrations.AddField(
            model_name='review',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='series.series', verbose_name='serial'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie', verbose_name='film'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie', verbose_name='film'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'series'), name='unique_user_series_rating'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('series__isnull', True)), models.Q(('movie__isnull', True), ('series__isnull', False)), _connector='OR'), name='rating_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'series'), name='unique_user_series_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('series__isnull', True)), models.Q(('movie__isnull', True), ('series__isnull', False)), _connector='OR'), name='review_exactly_one_target'),
        ),
    ]
