# Generated by Django 6.1.1 on 2026-09-07 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=150, verbose_name='nomi')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/%Y/%m/', verbose_name='rasm')),
                ('price', models.PositiveIntegerField(verbose_name='narx (cinepoint)')),
                ('stock', models.PositiveIntegerField(blank=True, help_text="Bo'sh qoldirilsa — cheksiz zaxira.", null=True, verbose_name='zaxira')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'mahsulot',
                'verbose_name_plural': 'mahsulotlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CinepointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Kredit uchun musbat, debet uchun manfiy son.', verbose_name='miqdor')),
                ('reason', models.CharField(choices=[('admin', 'Admin tomonidan'), ('movie_watch', "Film ko'rish"), ('review_approved', 'Sharh tasdiqlandi'), ('purchase', 'Xarid'), ('refund', 'Qaytarish')], max_length=20, verbose_name='sabab')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='izoh')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="qo'lda o'zgartirgan admin")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinepoint_transactions', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'cinepoint tranzaksiyasi',
                'verbose_name_plural': 'cinepoint tranzaksiyalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='shop_cinepo_user_id_9127d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('product_name', models.CharField(max_length=150, verbose_name='mahsulot nomi')),
                ('price_paid', models.PositiveIntegerField(verbose_name="to'langan narx (cinepoint)")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=10, verbose_name='holat')),
                ('admin_note', models.CharField(blank=True, help_text="Ichki foydalanish uchun — foydalanuvchiga ko'rinmaydi.", max_length=200, verbose_name='admin izohi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='yetkazilgan vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'buyurtma',
                'verbose_name_plural': 'buyurtmalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='shop_order_status_65feda_idx')],
            },
        ),
    ]
