# Generated by Django 6.1.1 on 2026-09-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='miqdor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_paid',
            field=models.PositiveIntegerField(verbose_name="to'langan narx (cinepoint, umumiy)"),
        ),
    ]
