# Generated by Django 6.1.1 on 2026-09-12 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=150, verbose_name='nomi')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('tagline', models.CharField(blank=True, help_text='Kartada nom ostida chiqadi. Masalan: «Eng ommabop tanlov».', max_length=200, verbose_name='qisqa shior')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('features', models.TextField(blank=True, help_text="Har qatorda bitta imkoniyat — kartada ✓ belgisi bilan chiqadi. DIQQAT: bu faqat ko'rsatish uchun, huquqlarni quyidagi belgilar boshqaradi.", verbose_name="imkoniyatlar ro'yxati")),
                ('level', models.PositiveSmallIntegerField(default=1, help_text="Rejalarni taqqoslash uchun — raqam qancha katta bo'lsa, reja shuncha yuqori.", verbose_name='daraja')),
                ('allows_premium_movies', models.BooleanField(default=True, help_text="Belgilansa, obunachi «premium» deb belgilangan filmlarni ko'ra oladi.", verbose_name='premium filmlarni ochadi')),
                ('has_badge', models.BooleanField(default=True, help_text="Profil va sharhlarda oltin «Premium» nishoni ko'rsatiladi.", verbose_name='nishon beradi')),
                ('is_ad_free', models.BooleanField(default=True, help_text="Kelajakdagi reklama bloklari bu obunachilarga ko'rsatilmaydi.", verbose_name='reklamasiz')),
                ('is_highlighted', models.BooleanField(default=False, help_text="Narxlar sahifasida ko'tarilgan holda, «Eng ommabop» lentasi bilan chiqadi.", verbose_name="ajratib ko'rsatilsin")),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'obuna rejasi',
                'verbose_name_plural': 'obuna rejalari',
                'ordering': ['order', 'level'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Masalan: «3 oy».', max_length=60, verbose_name='muddat nomi')),
                ('duration_days', models.PositiveIntegerField(help_text='Masalan: 30, 90, 365.', verbose_name='muddat (kun)')),
                ('price', models.PositiveIntegerField(verbose_name="narx (so'm)")),
                ('old_price', models.PositiveIntegerField(blank=True, help_text="To'ldirilsa, chegirmani ko'rsatish uchun ustidan chizilgan holda chiqadi.", null=True, verbose_name="eski narx (so'm)")),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscriptions.plan', verbose_name='reja')),
            ],
            options={
                'verbose_name': 'muddat narxi',
                'verbose_name_plural': 'muddat narxlari',
                'ordering': ['order', 'duration_days'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('plan_name', models.CharField(max_length=150, verbose_name='reja nomi')),
                ('duration_days', models.PositiveIntegerField(verbose_name='muddat (kun)')),
                ('price_paid', models.PositiveIntegerField(verbose_name="to'langan summa (so'm)")),
                ('status', models.CharField(choices=[('pending', 'Tasdiq kutilmoqda'), ('active', 'Faol'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=10, verbose_name='holat')),
                ('payment_note', models.CharField(blank=True, help_text="Masalan: karta oxirgi 4 raqami va o'tkazma vaqti.", max_length=200, verbose_name="to'lov haqida")),
                ('payment_receipt', models.ImageField(blank=True, help_text="O'tkazma skrinshoti — admin shuni tekshiradi.", null=True, upload_to='subscriptions/%Y/%m/', verbose_name="to'lov cheki")),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='boshlanish vaqti')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='tugash vaqti')),
                ('admin_note', models.CharField(blank=True, help_text='Rad etilganda foydalanuvchiga sabab sifatida yuboriladi.', max_length=200, verbose_name='admin izohi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='tekshirilgan vaqti')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='reja')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='tekshirgan admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'obuna',
                'verbose_name_plural': 'obunalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='subscriptio_status_16d834_idx'), models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_785d25_idx')],
            },
        ),
    ]
