# Generated by Django 6.1.1 on 2026-09-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_movie_age_rating_movie_downloads_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='original sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('short_description', models.CharField(blank=True, help_text="Bo'sh bo'lsa tavsifdan avtomatik olinadi.", max_length=300, verbose_name='qisqa tavsif')),
                ('poster', models.ImageField(blank=True, help_text='Vertikal (2:3), masalan 500x750.', null=True, upload_to='series/posters/%Y/%m/', verbose_name='poster')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='series/backdrops/%Y/%m/', verbose_name='backdrop')),
                ('trailer_url', models.URLField(blank=True, verbose_name='treyler havolasi')),
                ('release_year', models.PositiveSmallIntegerField(verbose_name='boshlangan yil')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, help_text="Serial hali davom etayotgan bo'lsa bo'sh qoldiring.", null=True, verbose_name='tugagan yil')),
                ('imdb_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='IMDb reytingi')),
                ('age_rating', models.CharField(blank=True, choices=[('0+', '0+ (barcha uchun)'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+ (faqat kattalar)')], default='', max_length=4, verbose_name='yosh chegarasi')),
                ('status', models.CharField(choices=[('announced', "E'lon qilingan"), ('ongoing', 'Davom etmoqda'), ('completed', 'Tugallangan')], default='ongoing', max_length=12, verbose_name='holat')),
                ('is_featured', models.BooleanField(default=False, verbose_name='tanlangan')),
                ('is_trending', models.BooleanField(default=False, verbose_name='trendda')),
                ('is_published', models.BooleanField(default=False, verbose_name='chop etilgan')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name="ko'rishlar soni")),
                ('categories', models.ManyToManyField(blank=True, related_name='series', to='movies.category', verbose_name='kategoriyalar')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='movies.country', verbose_name='davlat')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_series', to='movies.person', verbose_name='rejissyor')),
                ('genres', models.ManyToManyField(blank=True, related_name='series', to='movies.genre', verbose_name='janrlar')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='movies.language', verbose_name='til')),
            ],
            options={
                'verbose_name': 'serial',
                'verbose_name_plural': 'seriallar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='fasl raqami')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='nomi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='series/seasons/%Y/%m/', verbose_name='poster')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='yil')),
                ('is_published', models.BooleanField(default=True, verbose_name='chop etilgan')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.series', verbose_name='serial')),
            ],
            options={
                'verbose_name': 'fasl',
                'verbose_name_plural': 'fasllar',
                'ordering': ['series', 'number'],
            },
        ),
        migrations.CreateModel(
            name='SeriesCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=150, verbose_name='rol nomi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_roles', to='movies.person', verbose_name='aktyor')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='series.series', verbose_name='serial')),
            ],
            options={
                'verbose_name': 'serial aktyor roli',
                'verbose_name_plural': 'serial aktyorlar tarkibi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='acted_series', through='series.SeriesCast', to='movies.person', verbose_name='aktyorlar'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('episode_number', models.PositiveSmallIntegerField(default=1, verbose_name='epizod raqami')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='series/episodes/%Y/%m/', verbose_name='kadr rasmi')),
                ('video_url', models.URLField(blank=True, verbose_name='video havolasi')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='series/videos/%Y/%m/', verbose_name='video fayl')),
                ('download_url', models.URLField(blank=True, verbose_name='yuklab olish havolasi')),
                ('is_download_allowed', models.BooleanField(default=False, verbose_name='yuklab olishga ruxsat')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='davomiyligi (daqiqa)')),
                ('quality', models.CharField(choices=[('SD', 'SD'), ('HD', 'HD 720p'), ('FHD', 'Full HD 1080p'), ('4K', '4K Ultra HD')], default='HD', max_length=4, verbose_name='sifat')),
                ('air_date', models.DateField(blank=True, null=True, verbose_name='efirga uzatilgan sana')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name="ko'rishlar soni")),
                ('downloads_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='yuklab olishlar soni')),
                ('is_published', models.BooleanField(default=False, verbose_name='chop etilgan')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='movies.language', verbose_name='til')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.season', verbose_name='fasl')),
            ],
            options={
                'verbose_name': 'epizod',
                'verbose_name_plural': 'epizodlar',
                'ordering': ['season', 'episode_number'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='series_epis_is_publ_e91851_idx')],
                'constraints': [models.UniqueConstraint(fields=('season', 'episode_number'), name='unique_season_episode_number')],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('series', 'number'), name='unique_series_season_number'),
        ),
        migrations.AddConstraint(
            model_name='seriescast',
            constraint=models.UniqueConstraint(fields=('series', 'person'), name='unique_series_person_role'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_published', '-created_at'], name='series_seri_is_publ_43f52b_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_published', 'is_featured'], name='series_seri_is_publ_ff1a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['title'], name='series_seri_title_ee7844_idx'),
        ),
    ]
