# Generated by Django 6.1.1 on 2026-09-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_movies_pers_full_na_27c3fe_idx_movies_dire_full_na_bf449a_idx'),
        ('series', '0002_split_person_into_director_and_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_series', to='movies.director', verbose_name='rejissyor'),
        ),
    ]
