# Generated by Django 6.1.1 on 2026-09-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_copy_director_to_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='director',
        ),
    ]
