# Generated by Django 6.1.1 on 2026-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_remove_series_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3, verbose_name="o'rtacha reyting"),
        ),
        migrations.AddField(
            model_name='series',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='baholar soni'),
        ),
    ]
