# Generated by Django 6.1.1 on 2026-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_director'),
        ('series', '0007_series_avg_rating_series_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Faqat faol Premium obunasi bor foydalanuvchilar tomosha qila oladi.', verbose_name='premium'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_published', 'is_premium'], name='series_seri_is_publ_449a44_idx'),
        ),
    ]
