# Generated by Django 6.1.1 on 2026-09-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_countries_alter_movie_country'),
        ('series', '0008_series_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Bir nechta davlat tanlash mumkin.', related_name='series', to='movies.country', verbose_name='davlatlar'),
        ),
        migrations.AlterField(
            model_name='series',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_old', to='movies.country', verbose_name='davlat (eski)'),
        ),
    ]
