# Generated by Django 6.1.1 on 2026-09-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0010_copy_country_to_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='country',
        ),
    ]
