# Generated by Django 6.1.1 on 2026-09-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_movie_age_rating_movie_downloads_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MORE-MOVIE', max_length=80, verbose_name='sayt nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='logotip')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='favicon')),
                ('site_description', models.TextField(blank=True, verbose_name='sayt tavsifi')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='aloqa uchun email')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='mualliflik huquqi matni')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO sarlavha')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='SEO tavsif')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name="SEO kalit so'zlar")),
                ('google_analytics_id', models.CharField(blank=True, max_length=40, verbose_name='Google Analytics ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Yoqilsa, oddiy foydalanuvchilar uchun sayt vaqtincha yopiladi.', verbose_name='texnik xizmat rejimi')),
                ('maintenance_message', models.TextField(blank=True, help_text="Texnik xizmat rejimida foydalanuvchiga ko'rsatiladigan matn.", verbose_name='texnik xizmat xabari')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
            ],
            options={
                'verbose_name': 'sayt sozlamalari',
                'verbose_name_plural': 'sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='sarlavha')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='rasm')),
                ('link', models.URLField(blank=True, verbose_name='havola')),
                ('position', models.CharField(choices=[('homepage_hero', 'Bosh sahifa — hero'), ('homepage_banner', 'Bosh sahifa — banner'), ('movie_detail', 'Film sahifasi'), ('player', 'Player'), ('sidebar', 'Yon panel')], default='homepage_banner', max_length=20, verbose_name='joylashuv')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='boshlanish sanasi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('impressions', models.PositiveIntegerField(default=0, editable=False, verbose_name="ko'rsatilishlar")),
                ('clicks', models.PositiveIntegerField(default=0, editable=False, verbose_name='bosilishlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'bannerlar',
                'ordering': ['position', 'order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'position'], name='siteconfig__is_acti_70412e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='banner_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero', 'Hero'), ('continue', 'Davom ettirish'), ('trending', 'Trend'), ('popular', 'Mashhur'), ('new_releases', "Yangi qo'shilganlar"), ('top_rated', 'Yuqori reytingli'), ('featured', 'Tanlangan'), ('genres', 'Janrlar'), ('category', "Kategoriya bo'yicha")], max_length=20, unique=True, verbose_name='kalit')),
                ('title', models.CharField(max_length=100, verbose_name='sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='kichik sarlavha')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('item_limit', models.PositiveSmallIntegerField(default=14, verbose_name='elementlar soni')),
                ('category', models.ForeignKey(blank=True, help_text="Faqat 'Kategoriya bo'yicha' turi uchun.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_sections', to='movies.category', verbose_name='kategoriya')),
                ('movie', models.ForeignKey(blank=True, help_text="Faqat 'Hero' turi uchun — aniq bir filmni belgilash.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_sections', to='movies.movie', verbose_name='tanlangan film')),
            ],
            options={
                'verbose_name': "bosh sahifa bo'limi",
                'verbose_name_plural': "bosh sahifa bo'limlari",
                'ordering': ['order', 'id'],
            },
        ),
    ]
