# Generated by Django 6.1.1 on 2026-09-06 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='sarlavha')),
                ('message', models.TextField(max_length=2000, verbose_name='xabar matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/%Y/%m/', verbose_name='rasm')),
                ('notification_type', models.CharField(choices=[('info', "Ma'lumot"), ('promo', 'Aksiya'), ('update', 'Yangilanish')], default='info', max_length=10, verbose_name='turi')),
                ('link', models.URLField(blank=True, help_text='Ixtiyoriy -- bosilganda ochiladigan sahifa.', verbose_name='havola')),
                ('target', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('active', 'Faol foydalanuvchilar'), ('selected', 'Tanlangan foydalanuvchilar')], default='all', max_length=10, verbose_name='qamrov')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='yuborilgan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='yuboruvchi')),
                ('target_users', models.ManyToManyField(blank=True, help_text="Faqat qamrov 'Tanlangan foydalanuvchilar' bo'lganda ishlatiladi.", related_name='direct_notifications', to=settings.AUTH_USER_MODEL, verbose_name='tanlangan foydalanuvchilar')),
            ],
            options={
                'verbose_name': 'bildirishnoma',
                'verbose_name_plural': 'bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name="o'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="o'qilgan vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yetkazilgan')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='siteconfig.notification', verbose_name='bildirishnoma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'bildirishnoma qabul qiluvchisi',
                'verbose_name_plural': 'bildirishnoma qabul qiluvchilari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='siteconfig__created_124a90_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', 'is_read'], name='siteconfig__user_id_54b285_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationrecipient',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='unique_notification_recipient'),
        ),
    ]
