# Generated by Django 6.1.1 on 2026-09-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_notification_notificationrecipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('active', 'Faol foydalanuvchilar'), ('selected', 'Tanlangan foydalanuvchilar'), ('staff', 'Xodimlar')], default='all', max_length=10, verbose_name='qamrov'),
        ),
    ]
