# Generated by Django 6.1.1 on 2026-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_alter_notification_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card_holder',
            field=models.CharField(blank=True, max_length=100, verbose_name='karta egasi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card_number',
            field=models.CharField(blank=True, help_text="Obuna to'lovi uchun ko'rsatiladigan karta raqami.", max_length=25, verbose_name='karta raqami'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text="Obuna sahifasida foydalanuvchiga ko'rsatiladigan qo'shimcha izoh.", verbose_name="to'lov ko'rsatmasi"),
        ),
    ]
