# Generated by Django 6.1.1 on 2026-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0007_reorder_homepage_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='key',
            field=models.CharField(choices=[('hero', 'Hero'), ('continue', 'Davom ettirish'), ('premieres', 'Premyeralar'), ('movies', 'Kinolar'), ('cartoons', 'Multfilmlar'), ('series', 'Seriallar'), ('genres', 'Janrlar'), ('years', 'Yillar'), ('category', "Kategoriya bo'yicha")], max_length=20, unique=True, verbose_name='kalit'),
        ),
    ]
