# Generated by Django 6.1.1 on 2026-09-03 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nomi')),
                ('code', models.CharField(blank=True, max_length=3, verbose_name='ISO kodi')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'davlat',
                'verbose_name_plural': 'davlatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="qo'shilgan")),
            ],
            options={
                'verbose_name': 'sevimli',
                'verbose_name_plural': 'sevimlilar',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('icon', models.CharField(blank=True, help_text="Ixtiyoriy. Shablondagi ikonka to'plamidan kalit.", max_length=40, verbose_name='ikonka kaliti')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'janr',
                'verbose_name_plural': 'janrlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nomi')),
                ('code', models.CharField(blank=True, max_length=8, verbose_name='kod')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'til',
                'verbose_name_plural': 'tillar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='original sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('short_description', models.CharField(blank=True, help_text="Kartalar va hero bo'limida ko'rsatiladi. Bo'sh bo'lsa tavsifdan olinadi.", max_length=300, verbose_name='qisqa tavsif')),
                ('meta_description', models.CharField(blank=True, help_text="Qidiruv tizimlari uchun. Bo'sh bo'lsa qisqa tavsif ishlatiladi.", max_length=170, verbose_name='SEO meta description')),
                ('poster', models.ImageField(blank=True, help_text='Vertikal (2:3), masalan 500x750.', null=True, upload_to='posters/%Y/%m/', verbose_name='poster')),
                ('backdrop', models.ImageField(blank=True, help_text='Gorizontal (16:9), hero va detail sahifasi foni uchun.', null=True, upload_to='backdrops/%Y/%m/', verbose_name='backdrop')),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed havolasi.', verbose_name='treyler havolasi')),
                ('video_url', models.URLField(blank=True, help_text="To'g'ridan-to'g'ri MP4/HLS havolasi (qonuniy manba).", verbose_name='video havolasi')),
                ('video_file', models.FileField(blank=True, help_text='Serverga yuklangan qonuniy video. video_url dan ustun turadi.', null=True, upload_to='videos/%Y/%m/', verbose_name='video fayl')),
                ('download_url', models.URLField(blank=True, help_text='Faqat huquq egasi ruxsat bergan fayl havolasi.', verbose_name='yuklab olish havolasi')),
                ('release_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='chiqarilgan yil')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='davomiyligi (daqiqa)')),
                ('quality', models.CharField(choices=[('SD', 'SD'), ('HD', 'HD 720p'), ('FHD', 'Full HD 1080p'), ('4K', '4K Ultra HD')], default='HD', max_length=4, verbose_name='sifat')),
                ('imdb_rating', models.DecimalField(decimal_places=1, default=0, help_text='Tashqi manba reytingi (0-10). Foydalanuvchi reytingidan alohida.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='IMDb reytingi')),
                ('license_type', models.CharField(choices=[('public_domain', 'Public domain / Creative Commons'), ('licensed', 'Litsenziyalangan (huquq egasi ruxsati bor)'), ('trailer_only', "Faqat treyler (to'liq film yo'q)")], default='trailer_only', help_text="Kontentning huquqiy holati. Ko'rish va yuklash shunga qarab ochiladi.", max_length=20, verbose_name='litsenziya turi')),
                ('license_note', models.CharField(blank=True, help_text="Masalan: 'CC BY 3.0, Blender Foundation'.", max_length=200, verbose_name='litsenziya izohi')),
                ('is_download_allowed', models.BooleanField(default=False, help_text='Faqat huquq egasi ruxsat bergan fayllar uchun belgilang.', verbose_name='yuklab olishga ruxsat')),
                ('is_featured', models.BooleanField(default=False, help_text="Bosh sahifadagi hero va 'Featured' bo'limida ko'rsatiladi.", verbose_name='tanlangan')),
                ('is_published', models.BooleanField(default=False, help_text="Belgilanmagan bo'lsa film saytda ko'rinmaydi.", verbose_name='chop etilgan')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name="ko'rishlar soni")),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3, verbose_name="o'rtacha reyting")),
                ('rating_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='baholar soni')),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'filmlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=150, verbose_name='rol nomi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'aktyor roli',
                'verbose_name_plural': 'aktyorlar tarkibi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('full_name', models.CharField(max_length=150, verbose_name="to'liq ism")),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/', verbose_name='surat')),
                ('bio', models.TextField(blank=True, verbose_name='qisqacha')),
            ],
            options={
                'verbose_name': 'shaxs',
                'verbose_name_plural': 'shaxslar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/', verbose_name='rasm')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='izoh')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'kadr',
                'verbose_name_plural': 'kadrlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_seconds', models.PositiveIntegerField(default=0, verbose_name="to'xtagan joy (soniya)")),
                ('is_finished', models.BooleanField(default=False, verbose_name='tugatilgan')),
                ('watched_at', models.DateTimeField(auto_now=True, verbose_name="oxirgi ko'rish")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="birinchi ko'rish")),
            ],
            options={
                'verbose_name': "ko'rish tarixi",
                'verbose_name_plural': "ko'rish tarixi",
                'ordering': ['-watched_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="qo'shilgan")),
            ],
            options={
                'verbose_name': 'watchlist elementi',
                'verbose_name_plural': 'watchlist',
                'ordering': ['-added_at'],
            },
        ),
    ]
