# Generated by Django 6.1.1 on 2026-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(blank=True, choices=[('0+', '0+ (barcha uchun)'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+ (faqat kattalar)')], default='', max_length=4, verbose_name='yosh chegarasi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='yuklab olishlar soni'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Faqat premium foydalanuvchilar uchun (hozircha belgi sifatida).', verbose_name='premium'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(default=False, help_text="Bosh sahifadagi «Trend» bo'limiga qo'lda qo'shish.", verbose_name='trendda'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, help_text="Aniq sana ma'lum bo'lsa. Yil maydoni asosiy bo'lib qoladi.", null=True, verbose_name='chiqarilgan sana'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='rasm')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
            ],
            options={
                'verbose_name': 'kategoriya',
                'verbose_name_plural': 'kategoriyalar',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='movies_cate_is_acti_8e18e0_idx')],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.category', verbose_name='kategoriyalar'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_published', 'is_trending'], name='movies_movi_is_publ_96c4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_published', 'is_premium'], name='movies_movi_is_publ_cb4e56_idx'),
        ),
    ]
