# Generated by Django 6.1.1 on 2026-09-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_age_rating_movie_downloads_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='download_url',
            field=models.URLField(blank=True, help_text='Faqat huquq egasi ruxsat bergan fayl havolasi.', null=True, verbose_name='yuklab olish havolasi'),
        ),
    ]
