# Generated by Django 6.1.1 on 2026-09-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_split_person_into_director_and_actor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='director',
            new_name='movies_dire_full_na_bf449a_idx',
            old_name='movies_pers_full_na_27c3fe_idx',
        ),
    ]
