# Generated by Django 6.1.1 on 2026-09-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_movies_pers_full_na_27c3fe_idx_movies_dire_full_na_bf449a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('SD', 'SD'), ('HD', 'HD 720p'), ('FHD', 'Full HD 1080p'), ('4K', '4K Ultra HD')], default='FHD', max_length=4, verbose_name='sifat')),
                ('video_url', models.URLField(blank=True, help_text="To'g'ridan-to'g'ri MP4/HLS havolasi (qonuniy manba).", verbose_name='video havolasi')),
                ('video_file', models.FileField(blank=True, help_text='Serverga yuklangan fayl — havoladan ustun turadi.', null=True, upload_to='videos/%Y/%m/', verbose_name='video fayl')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movies.movie', verbose_name='film')),
            ],
            options={
                'verbose_name': 'video sifati',
                'verbose_name_plural': 'video sifatlari',
                'constraints': [models.UniqueConstraint(fields=('movie', 'quality'), name='unique_movie_video_quality')],
            },
        ),
    ]
