# Generated by Django 6.1.1 on 2026-09-12 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movievideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, help_text='Bir nechta rejissyor tanlash mumkin.', related_name='directed_movies', to='movies.director', verbose_name='rejissyorlar'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies_old', to='movies.director', verbose_name='rejissyor (eski)'),
        ),
    ]
