# Generated by Django 6.1.1 on 2026-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_premiere',
            field=models.BooleanField(db_index=True, default=False, help_text="Bosh sahifadagi «Premyeralar» bo'limida e'lon qilinadi.", verbose_name='premyera'),
        ),
        migrations.AddField(
            model_name='movie',
            name='kind',
            field=models.CharField(choices=[('movie', 'Kino'), ('cartoon', 'Multfilm')], db_index=True, default='movie', help_text="Bosh sahifadagi «Kinolar» va «Multfilmlar» bo'limlari shunga qarab ajraladi.", max_length=10, verbose_name='turi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='premiere_date',
            field=models.DateField(blank=True, help_text="Ixtiyoriy. Kelajakdagi sana «tez orada» deb ko'rsatiladi.", null=True, verbose_name='premyera sanasi'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_published', 'kind'], name='movies_movi_is_publ_412079_idx'),
        ),
    ]
