# Generated by Django 6.1.1 on 2026-09-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_is_premiere_movie_kind_movie_premiere_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Bir nechta davlat tanlash mumkin.', related_name='movies', to='movies.country', verbose_name='davlatlar'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_old', to='movies.country', verbose_name='davlat (eski)'),
        ),
    ]
