# Generated by Django 6.1.1 on 2026-09-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('SD', 'SD 480p'), ('HD', 'HD 720p'), ('FHD', 'Full HD 1080p'), ('4K', '4K Ultra HD')], default='HD', max_length=4, verbose_name='sifat'),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='quality',
            field=models.CharField(choices=[('SD', 'SD 480p'), ('HD', 'HD 720p'), ('FHD', 'Full HD 1080p'), ('4K', '4K Ultra HD')], default='FHD', max_length=4, verbose_name='sifat'),
        ),
    ]
